Tlv library first version
fl0rek/ProjektTIN pull request #48
Opened 2017-05-14 12:22 UTC by izaya0

2017-05-21 17:08 UTC, fl0rek requested changes
Most of the comments are related to coding style - please try to follow google coding style, but these are minor.

Other are regarding some thing being unclear, here probably some kind of comment would be nice.

Finally, I think adding function declaration comments is necessary, at least for public functions.

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +		void add(const unsigned int tag, const bool embedded_tags_flag, const unsigned char size,
add function declaration comment at least for public methods. For example it's not clear what `embedded_tags_flag` is

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +		//std::vector<unsigned char> get(const unsigned int tag);
Don't commit commented code (or provide reason why it should be commited)

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +			TlvNode(const unsigned int tag, const unsigned char size, const unsigned char * const data);
While this is private struct it would be nice to also add function declaration comments here (MINOR)

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +		const int EMBEDDED_TAGS_FLAG_POS = 3;
Constants should use kVariable naming scheme. (or unerscore_case but please don't use capitals and underscores, this isn't define)

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +void Tlv::deleteNode(const TlvNode * const node)
Braces on the same line, there's like 6 lines of core here and function takes ¬20. MINOR I guess

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +		void add(const unsigned int tag, const bool embedded_tags_flag, const unsigned char size,
Also -- why tag is `int`? What about tags != 4 bytes?

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +#include "TlvObject.h"
header order.
TlvObject should be first, then empty line then others. 
MINOR

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +class Tlv
Why is this file named `TlvObject` even though it provides `Tlv` class?

2017-05-21 17:08 UTC, fl0rek commented on libtlv/include/TlvObject.h
> +#pragma once
This  should be in the first line

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +void Tlv::pushTagToBuffer(const unsigned int tag, vector<unsigned char> &buffer) const
This function kind of looks like it's only supporting 3byte tags?

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +		buffer.push_back((node->data_)[i]);
You could resize vector and copy everything in one go instead of doing it byte by byte

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +       	vector<unsigned char> buffer;
Indentation

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +void Tlv::pushToBuffer(const TlvNode * const node, vector<unsigned char> &buffer) const
What's the difference between this and `pushDataToBuffer`? Both seem to push some kind of data to some kind of buffer. Be more specific please.

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObject.cpp
> +vector<unsigned char> Tlv::findTagData(const unsigned int tag) const
This function seems to return a copy of data so I think it should be named `getTagData` as not to cause confusion.

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObjectTests.cpp
> +#include "TlvObject.h"
Header order

2017-05-21 17:08 UTC, fl0rek commented on libtlv/src/TlvObjectTests.cpp
> +	o.add(14, 1, 13, tt);
What this one means here? I see you've defined library constants, please use them for clarity.

2017-05-22 20:23 UTC, izaya0 commented
I pushed new version

2017-05-23 14:00 UTC, fl0rek approved these changes
Ok

2017-05-23 14:03 UTC, ASobolewski approved these changes

2017-05-23 15:26 UTC, merged